# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img',
            field=models.FileField(default=b'/img/xxx.xxx', upload_to=user.models.get_upload_path),
        ),
    ]
